# Generated by Django 3.1.3 on 2020-11-16 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('website', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('size', models.CharField(choices=[('xss', '1-9'), ('xs', '10-99'), ('s', '100-499'), ('n', '500-1000'), ('l', '1000-1999'), ('xl', '2000-10000')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=128)),
                ('job_description', models.TextField()),
                ('requirements', models.TextField()),
                ('rewards', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hryar.company')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('resume', models.BinaryField()),
                ('phone_number', models.CharField(max_length=11)),
                ('expected_salary', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applyment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('r', 'rejected'), ('i', 'in progress '), ('h', 'hired')], max_length=20)),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hryar.person')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hryar.position')),
            ],
        ),
    ]
