# Generated by Django 3.1.3 on 2020-11-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hryar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
